config/routes.rb
Pollster::Application.routes.draw do
  resources :polls do
    resources :questions 
  end

  resources :questions, :only => [] do 
    resources :answers
  end

root :to => 'polls#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :description, :question
  belongs_to :question

  def self.to_csv(qid) 
      csv = ""
      csv << column_names.to_s << "\n"
      results = find_all_by_question_id(qid)
        if results.is_a?(Answer)
           csv << results.attributes.values_at(*column_names).to_s << "\n"
        else 
          results.each do |answer|
          csv << answer.attributes.values_at(*column_names).to_s << "\n"
          end
        end  
      csv
  end
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :title, :edit_url, :share_url
  has_many :questions
  has_many :answers, :through => :questions
  
  before_create :set_urls  

  def to_param
    self.edit_url
  end


private
  def format_url
    ('a'..'z').to_a.shuffle.sample(5).join
  end

  def set_urls
    self.edit_url = format_url
    self.share_url = format_url
  end



end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :description, :format
  belongs_to :poll
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def index
  # @answers = Answer.find_by_question_id(params[:question_id])
  # @answers = Answer.to_csv
  @answers = Answer.order(:description)
    respond_to do |format|
      format.csv {render text: @answers.to_csv(params[:question_id])}
    end
  end

  def create
    # @poll = Poll.find(params[:poll_id])
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(params[:answer])
    answered_questions << @question.id
    p answered_questions
    # if cookies[:voted] == nil 
    #   cookies[:voted] = ""
    # else cookies[:voted].length >= 1
    #   p cookies[:voted]
    # end
    # if @answer.save
    #   x = cookies[:voted]
    #   x <<  @question.id.to_s << ","
    #   cookies[:voted] = x
    #   puts "*"*100
    #   p cookies[:voted]
      redirect_to :back
    # end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  after_filter :save_cookie
  helper_method :answered_questions

  private

  def answered_questions
    @answered_questions ||= if cookies[:answered_questions]
      cookies[:answered_questions].split(";").collect(&:to_i)
    else
      []
    end
  end

  def save_cookie
    cookies[:answered_questions] = answered_questions.join(";")
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  def index
    @polls = Poll.all
  end

  def create
    @poll = Poll.new(params[:poll])
    if @poll.save
      redirect_to edit_poll_path(@poll.edit_url)
    end
  end

  def new
    @poll = Poll.new
  end

  def edit 
    @poll = Poll.find_by_edit_url(params[:id])
    # if @poll.questions.new.nil?
    # @question = @poll.questions.new
  end

  def update
    @poll = Poll.update_attributes(params[:poll])
  end

  def show
    @poll = Poll.find_by_share_url(params[:id])
    render :layout => 'show.html.erb'
  end

  def destroy
    @poll = Poll.find_by_edit_url(params[:id])
    @poll.destroy
    redirect_to polls_url
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :find_poll

  def create
    @question = @poll.questions.new(params[:question])

    if @question.save
      redirect_to edit_poll_path(@poll.edit_url)
    else
      render 'polls/edit'
    end
  end

  def edit
    @question = @poll.questions.find(params[:id])
  end

  def update
    @question = @poll.questions.find(params[:id])
    @question.update_attributes(params[:question])
    head :ok
  end

  def show
    puts "hello"
  end

  def destroy
    p @poll
    @question = @poll.questions.find(params[:id])
    @question.destroy
    redirect_to(:back)
  end

  private

  def find_poll
    if params[:poll_id] =~ /^\d+$/
      @poll = Poll.find(params[:poll_id])
    else
      @poll = Poll.find_by_edit_url(params[:poll_id])
    end
      p params[:poll_id]
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def already_answered(question)
    answered_questions.include? @question.id
  end
end

app/views/answers/_form.html.erb
<%= form_for [@question, Answer.new] do |f| %>
    <div class="field">
      <%= f.text_area :description, rows: 2, class: 'span8' %>
    </div>
    <div class="actions">
      <% if already_answered(@question) %>
        You have now voted or already voted.
      <% else %>
        <%= f.submit class: 'btn' %>
      <% end %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pollster" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Pollster", polls_path, :class => 'brand' %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "New Poll", new_poll_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container" style="margin-top:50px;">
        <div class="row">
          <div class="span9">
             <%= yield %>
          </div>
        </div><!--/row-->


    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  <footer>
    <div id = "inside"
      <p>&copy; DJ B-hott Production</p>
    </div>
  </footer>

  </body>

</html>

app/views/layouts/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pollster" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    
    <div class="container" style="margin-top:50px;">
        <div class="row">
          <div class="span9">
             <%= yield %>
          </div>
        </div><!--/row-->


    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  <footer>
      <p>&copy; DJ B-hott Production</p>
  </footer>

  </body>

</html>

app/views/polls/edit.html.erb
<h2>Editing Poll - edit the poll by clicking on it's descriptions</h2>

<table class = "table">
  <thead>
    <tr>
      <th>
        Title
      </th>
      <th>
        Question
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class = "lead"><%= best_in_place @poll, :title %></td>
      <td>
        <% @poll.questions.each do |question| %>
        <div class="well">
          <%= best_in_place question, :description, remote: :true %>
          
          <%= link_to 'Destroy', poll_question_path(@poll.edit_url, question.id), class: 'btn btn-mini btn-primary', method: :delete, data: { confirm: 'Are you sure?'} %>
          <%= link_to 'Answers',  question_answers_path(question.id) + ".csv", class: 'btn btn-mini btn-primary'%>
        </div>  
        
      <%end%>      
      </td>
    </tr>
  </tbody>
</table>

<div class = 'row'>
    <h2>Question</h2>
    <%= render 'questions/form' %>
</div>

app/views/polls/index.html.erb
<h1>Pollster</h1>

<% @polls.each do |poll| %>
<table class="table">
  <thead>
    <tr>
      <th>
        Title
      </th>
    </tr>
    <tbody>
      <tr>
        <td><%= poll.title %></td>
        <td>
          <%= link_to 'Show', poll_path(poll.share_url) %> | 
          <%= link_to 'Edit', edit_poll_path(poll.edit_url) %> | 
          <%= link_to 'Destroy', poll_path(poll.edit_url), method: :delete, data: { confirm: 'Are you sure?' } %> |
          <%= link_to 'Short Url', poll_path(poll.edit_url) %>
        </td>
      </tr>
    </tbody>
  </thead>
</table>
    
<% end %>

app/views/polls/new.html.erb
<h2> New Poll </h2>

<%= form_for(@poll) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>

<% end %>

app/views/polls/show.html.erb
<h1><%= @poll.title%></h1>
<% @poll.questions.each do |question| %>
<% p question %>
<p class = "lead">
    <% @question = question %>
    <%= @question.description.gsub(/\n/, '<br/>').html_safe %>
</p>
  <%= render 'answers/form'%>
<%end%>

app/views/questions/_form.html.erb
<%= form_for [@poll, @question = Question.new] do |f| %>
  <div class="field">
    <%= f.text_area :description, rows: 2, class: 'span8' %>
  </div>
  <div class="actions">
    <%= f.radio_button(:format, "Multiple Choice")%> Multiple Choice
    <%= f.radio_button(:format, "Open Ended")%>  Open Ended
    <%= f.submit  class: 'btn' %>
    <%= link_to 'Done Editing', polls_path, class: 'btn btn-primary'  %>
  </div>
<% end %>